//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmentiesMaster
    {
        public string EventName { get; set; }
        public string Laun { get; set; }
        public string Hall { get; set; }
        public string Music { get; set; }
        public string Tent { get; set; }
        public string Parlour { get; set; }
        public string Catering { get; set; }
    
        public virtual EventMaster EventMaster { get; set; }
    }
}
