//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMaster
    {
        public int BookingId { get; set; }
        public string BookedBy { get; set; }
        public string EventList { get; set; }
        public Nullable<System.DateTime> BookDate { get; set; }
        public Nullable<int> GuestCount { get; set; }
        public string Hall { get; set; }
        public string Lawn { get; set; }
        public string Music { get; set; }
        public string Tent { get; set; }
        public string Parlour { get; set; }
        public string Catering { get; set; }
        public Nullable<double> TotalAmount { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
