//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsMaster
    {
        public int SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string Message { get; set; }
        public string ComplainBy { get; set; }
        public string Date_Time { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
