//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMaster
    {
        public int Contact_Id { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string EmailId { get; set; }
        public string MobNo { get; set; }
        public string Message { get; set; }
        public string Date_Time { get; set; }
    }
}
