//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wedding_PlannerEntities : DbContext
    {
        public Wedding_PlannerEntities()
            : base("name=Wedding_PlannerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmentiesMaster> AmentiesMasters { get; set; }
        public virtual DbSet<AreaMaster> AreaMasters { get; set; }
        public virtual DbSet<BookingMaster> BookingMasters { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<ComplaintsMaster> ComplaintsMasters { get; set; }
        public virtual DbSet<ContactMaster> ContactMasters { get; set; }
        public virtual DbSet<EnquiryMaster> EnquiryMasters { get; set; }
        public virtual DbSet<EventMaster> EventMasters { get; set; }
        public virtual DbSet<FeedBackMaster> FeedBackMasters { get; set; }
        public virtual DbSet<LoginMaster> LoginMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<SendEmailMaster> SendEmailMasters { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
    }
}
