//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wedding_Planner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.BookingMasters = new HashSet<BookingMaster>();
            this.ComplaintsMasters = new HashSet<ComplaintsMaster>();
            this.FeedBackMasters = new HashSet<FeedBackMaster>();
        }
    
        public string Name { get; set; }
        public string Gender { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> Related_City_Id { get; set; }
        public Nullable<int> Related_Area_Id { get; set; }
        public string Address { get; set; }
        public string Picture_File_Name { get; set; }
        public Nullable<System.DateTime> DateTime_Of_Reg { get; set; }
        public Nullable<bool> Is_Del { get; set; }
    
        public virtual AreaMaster AreaMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingMaster> BookingMasters { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintsMaster> ComplaintsMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBackMaster> FeedBackMasters { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
    }
}
